### ISSUE TITLE
Vignette compilation failed

### ISSUE THREAD

**Issue by simoncarrignon** [MengLeZhang/socialFrontiers#13]
When trying to render [the vignettte](https://github.com/MengLeZhang/socialFrontiers/blob/master/vignettes/Detecting-frontiers-in-Barnet.Rmd) , compilation fail with this error:
```
Error in inla(form, family = "binomial", data = data.temp, Ntrials = Ntrials,  :
  unused argument (control.results = list(return.marginals.predictor = TRUE))
```
Very likely due to the fact that I am using the testing version of  INLA; will have a deeper look at what's happening.

**Comment by simoncarrignon** [comment]
Oh indeed, sorry I just realize that's what the "inlahotfix" branch is doing!

**Comment by simoncarrignon** [comment]
I found the commit where they removed that: https://github.com/hrue/r-inla/commit/943d24e91dc44b57ae407be5ca09e2e2f64da965
I implemented a small test to check INLA version and if its version that comes after this commit then we dont use the parameter, if the version is earlier then we keep it. Not very eleguant yet, I guess that it would be better to just remove the use of control.results at some points. Implementation is available in pull request #14

**Comment by MengLeZhang** [comment]
That's literally amazing! Thanks for checking out the commit where this happened. Got a meeting with one of the original method authors to double check that removing control.results is not problematic. 

We're having some trouble with getting earlier versions of INLA (help appreciated). I like the idea of keeping it to earlier versions of INLA to avoid hotfixes every time INLA changes something.

**Comment by MengLeZhang** [comment]
Look good to me. Pull request accepted and closing issue before big merge
